FROM python:3.13-slim-bookworm

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

# build the uv environment with all dependencies
RUN uv sync 

# copy the current directory contents into the container 
COPY . .

# install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# expose port 80
EXPOSE 80


