name: bss
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - greenlet=3.1.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libcxxabi=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libpq=17.4
  - librdkit=2024.09.6
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-base=3.10.1
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.2.3
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - polars=1.24.0
  - pthread-stubs=0.4
  - pycairo=1.27.0
  - pycparser=2.22
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.13
  - pytz=2024.1
  - qhull=2020.2
  - rdkit=2024.09.6
  - readline=8.2
  - reportlab=4.3.1
  - requests=2.32.3
  - rlpycairo=0.2.0
  - six=1.17.0
  - sqlalchemy=2.0.38
  - tk=8.6.13
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - neattime==0.0.4
