name: bss
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - libcxx=19.1.7
  - libexpat=2.6.4
  - libffi=3.4.2
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.13.2
  - python_abi=3.13
  - readline=8.2
  - requests=2.32.3
  - tk=8.6.13
  - tzdata=2025a
  - urllib3=2.3.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - neattime==0.0.4
